feat(pfctl): add support custom profile rules

diff --git a/plugins/pfctl/bin/vpn-net b/plugins/pfctl/bin/vpn-net
--- a/plugins/pfctl/bin/vpn-net
+++ b/plugins/pfctl/bin/vpn-net
@@ -24,11 +24,10 @@
 set -euo pipefail
 
 SCRIPTNAME=$(basename "$0")
-SCRIPT_DIR=$(dirname $( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd))
+SCRIPT_DIR=$(dirname $(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" &>/dev/null && pwd))
 
 # List of IP address of VPN server.
 declare -a VPN_IP=()
-VPN_PORT=2194
 # List of utun interface as gateways.
 declare -a UTUN_IFACE=()
 # DNS resolver for mapping domain names to IP addresses.
@@ -38,6 +37,9 @@ declare -a HOSTS=()
 # CIDRs to bypass VPN, ensure to add VPN server IP address as well.
 declare -a IP_ADDRESSES=("192.168.1.0/24" "192.168.0.0/24" "192.168.8.0/24")
 ENABLE_ROUTING=
+
+# The pfctl profile name
+PROFILE_NAME="vpn.force"
 
 anchor_name="doty-bitmask"
 
@@ -58,6 +60,7 @@ ${FMT_BLUE}Options:${FMT_RESET}
     ${FMT_YELLOW}-a, --ip${FMT_RESET}                                               CIDRs to bypass VPN, ensure to add VPN server IP address as well.
     ${FMT_YELLOW}-d, --dns${FMT_RESET}                                              DNS resikver for mappung domain names to IP address (default: $(fmt_code "1.1.1.1")).
     ${FMT_YELLOW}-r, --route${FMT_RESET}                                            Indicates whether to enable routing table to bypass VPN for specified IP address.
+    ${FMT_YELLOW}-P, --profile${FMT_RESET}                                          The pfctl profile rules to be used.
     ${FMT_YELLOW}-v, --verbose${FMT_RESET}                                          Show verbose message.
     ${FMT_YELLOW}-h, --help${FMT_RESET}                                             Display this message.
 
@@ -96,7 +99,7 @@ command_exists() {
 }
 
 prompt() {
-  printf '%s%s%s' $FMT_YELLOW $FMT_RESET "$1"
+  printf '%s%s%s' "$FMT_YELLOW" "$FMT_RESET" "$1"
   read -p " ${FMT_BLACK}[y/N]${FMT_RESET} ${FMT_BOLD}" a
   printf "${FMT_RESET}"
   if [[ $a == "y" || $a == "Y" ]]; then
@@ -114,7 +117,7 @@ fmt_code() {
   is_tty && printf '\033[2m%s\033[22m\n' "$*" || printf '`%s`\n' "$*"
 }
 
-debug(){
+debug() {
   if [ ! -z $_verbose ]; then
     printf '%s%s%s\n' "${FMT_BOLD}${FMT_PURPLE}" "$1" "${FMT_RESET}${FMT_RESET}" >&2
     if [ "$#" -gt 1 ]; then
@@ -148,7 +151,7 @@ fatal() {
   error "$2"
   echo
   echo_red "[!] Exiting..."
-  exit ${1:1}
+  exit "${1:1}"
 }
 
 echo_green() {
@@ -176,7 +179,6 @@ separator_gray() {
   printf -- "${FMT_BOLD}${FMT_GRAY}-${FMT_RESET}%.0s" {1..80}
   echo ""
 }
-
 
 setup_color() {
   # Only use colors if connected to a terminal
@@ -223,7 +225,7 @@ apply_rules() {
   if [ "$answer" = "Y" ] || [ "$answer" = 'y' ] || [ -z "$answer" ]; then
     echo "$fw_rules" | pfctl -a $anchor_name -mf -
   else
-      echo_yellow "  ABORTED"
+    echo_yellow "  ABORTED"
   fi
 
   echo
@@ -231,10 +233,10 @@ apply_rules() {
 
 start() {
   # Find default public interface. If using WiFi, it's usually "en0".
-  ext_iface=$(route -n get -net default | grep interface | awk '{print $2}' ||  echo "en0")
+  ext_iface=$(route -n get -net default | grep interface | awk '{print $2}' || echo "en0")
   # vpn_ip=$(scutil --nc show Ivacy | grep 'CommRemoteAddress' | cut -d' ' -f 5)
 
-  info "Using default interface \"${ext_iface}\""
+  info "Using profile \"${PROFILE_NAME}\" for default interface \"${ext_iface}\""
 
   if [ ! -z "$ENABLE_ROUTING" ]; then
     gateway=$(netstat -nr | grep default | grep "$ext_iface" | awk '{print $2}' | head -1)
@@ -244,7 +246,7 @@ start() {
     if [[ ${#HOSTS[@]} -gt 0 ]]; then
       for website in ${HOSTS[*]}; do
         debug "Resolving $website"
-        for ip in $(dig @${DNS_RESOLVER} +short "${website}" | grep '^[.0-9]*$'); do
+        for ip in $(dig @"${DNS_RESOLVER}" +short "${website}" | grep '^[.0-9]*$'); do
           debug "Resolving $website as $ip"
 
           if ! (printf '%s\n' "${IP_ADDRESSES[*]}" | grep -q "$ip"); then
@@ -261,9 +263,9 @@ start() {
     done
   fi
 
-  ifconfig ${ext_iface} down
+  ifconfig "${ext_iface}" down
   route flush
-  ifconfig ${ext_iface} up
+  ifconfig "${ext_iface}" up
 
   # Disable pf
   pfctl -d 2>/dev/null || true
@@ -273,7 +275,8 @@ start() {
   # Enable pf
   pfctl -e 2>/dev/null || true
 
-  rules=$(cat <<EOF
+  rules=$(
+    cat <<EOF
 # Options
 set block-policy drop
 set fingerprints "/etc/pf.os"
@@ -290,7 +293,7 @@ $(cat "/etc/pf.conf")
 
 anchor "${anchor_name}"
 EOF
-)
+  )
 
   # Enable pflog
   # Create a pflog interface and monitor all packets logged on it:
@@ -302,31 +305,31 @@ EOF
   if [ -z "$log_iface" ]; then
     log_iface=$(ifconfig pflog create)
   fi
-  if [ -z "$monitor_iface" ] || [ "$monitor_iface" == "$log_iface"  ]; then
+  if [ -z "$monitor_iface" ] || [ "$monitor_iface" == "$log_iface" ]; then
     monitor_iface=$(ifconfig pflog create)
   fi
-  if [ -z "$block_iface" ] || [ "$monitor_iface" == "$block_iface"  ]; then
+  if [ -z "$block_iface" ] || [ "$monitor_iface" == "$block_iface" ]; then
     block_iface=$(ifconfig pflog create)
   fi
-  ifconfig $log_iface up
-  ifconfig $monitor_iface up
-  ifconfig $block_iface up
+  ifconfig "$log_iface" up
+  ifconfig "$monitor_iface" up
+  ifconfig "$block_iface" up
 
   # load a pf config equal to "set skip on lo0" + /etc/pf.conf + anchor "dotybitmask"
   debug "Applying rules..." "$rules"
   echo -e "$rules" | pfctl -ef -
 
-  info "Patch rules.." "${SCRIPT_DIR}/pf.anchors/vpn.force.rules"
+  info "Patch rules.." "${SCRIPT_DIR}/pf.anchors/${PROFILE_NAME}.rules"
   add_rule "$(
-    cat ${SCRIPT_DIR}/pf.anchors/vpn.force.rules \
-      | sed "7s/^vpn_ip \=.*$/vpn_ip = \"${VPN_IP[*]}\"/" \
-      | sed "7s/^vpn_port \=.*$/vpn_port = \"${VPN_PORT[*]}\"/" \
-      | sed "11s/^ext_iface \=.*$/ext_iface = \"${ext_iface}\"/" \
-      | sed "13s/^log_iface \=.*$/log_iface = \"${log_iface}\"/" \
-      | sed "14s/^monitor_iface \=.*$/monitor_iface = \"${monitor_iface}\"/" \
-      | sed "15s/^block_iface \=.*$/block_iface = \"${block_iface}\"/" \
-      | sed "17s/^table <gateways>.*$/table <gateways> const { $(echo "${UTUN_IFACE[*]}" | sed "s/ /, /") }/" \
-      | sed "s/ utun_iface / ${UTUN_IFACE[*]} /"
+    cat "${SCRIPT_DIR}/pf.anchors/${PROFILE_NAME}.rules" |
+      sed "7s/^vpn_ip \=.*$/vpn_ip = \"${VPN_IP[*]}\"/" |
+      sed "8s/^vpn_port \=.*$/vpn_port = \"${VPN_PORT[*]}\"/" |
+      sed "11s/^ext_iface \=.*$/ext_iface = \"${ext_iface}\"/" |
+      sed "13s/^log_iface \=.*$/log_iface = \"${log_iface}\"/" |
+      sed "14s/^monitor_iface \=.*$/monitor_iface = \"${monitor_iface}\"/" |
+      sed "15s/^block_iface \=.*$/block_iface = \"${block_iface}\"/" |
+      sed "17s/^table <gateways>.*$/table <gateways> const { $(echo "${UTUN_IFACE[*]}" | sed "s/ /, /") }/" |
+      sed "s/ utun_iface / ${UTUN_IFACE[*]} /"
   )"
 
   apply_rules || error "Unable to apply rules"
@@ -401,69 +404,73 @@ if [ -z "$__commands" ]; then
 fi
 
 case $__commands in
-  start)
-    # Parse arguments as options
-    while [[ $# -gt 0 ]]; do
-      case $1 in
-      -i | --vpn-ip)
-        VPN_IP+=("$2")
-        shift
-        shift
-        ;;
-      -p | --vpn-port)
-        VPN_PORT+=("$2")
-        shift
-        shift
-        ;;
-     -a | --ip)
-        IP_ADDRESSES+=("$2")
-        shift
-        shift
-        ;;
-      -h | --host)
-        HOSTS+=("${2}")
-        shift
-        shift
-        ;;
-      -d | --dns)
-        DNS_RESOLVER="${2}"
-        shift
-        shift
-        ;;
-      -r | --route)
-        ENABLE_ROUTING=1
-        shift
-        ;;
-      *)
-        UTUN_IFACE+=("$1")
-        shift
-        ;;
-      esac
-    done
+start)
+  # Parse arguments as options
+  while [[ $# -gt 0 ]]; do
+    case $1 in
+    -i | --vpn-ip)
+      VPN_IP+=("$2")
+      shift
+      shift
+      ;;
+    -p | --vpn-port)
+      VPN_PORT+=("$2")
+      shift
+      shift
+      ;;
+    -a | --ip)
+      IP_ADDRESSES+=("$2")
+      shift
+      shift
+      ;;
+    -h | --host)
+      HOSTS+=("${2}")
+      shift
+      shift
+      ;;
+    -d | --dns)
+      DNS_RESOLVER="${2}"
+      shift
+      shift
+      ;;
+    -r | --route)
+      ENABLE_ROUTING=1
+      shift
+      ;;
+    -P | --profile)
+      PROFILE_NAME="${2}"
+      shift
+      shift
+      ;;
+    *)
+      UTUN_IFACE+=("$1")
+      shift
+      ;;
+    esac
+  done
 
-    if [[ ${#VPN_IP[@]} -eq 0 ]]; then
-      error "missing required ${FMT_BOLD}VIP address of VPN server${FMT_RESET}"
-      echo
-      help
-      exit 2
-    fi
+  if [[ ${#VPN_IP[@]} -eq 0 ]]; then
+    error "missing required ${FMT_BOLD}VIP address of VPN server${FMT_RESET}"
+    echo
+    help
+    exit 2
+  fi
 
-    if [[ ${#UTUN_IFACE[@]} -eq 0 ]]; then
-      error "missing required ${FMT_BOLD}Vutun interface gateways${FMT_RESET}"
-      echo
-      help
-      exit 2
-    fi
+  if [[ ${#UTUN_IFACE[@]} -eq 0 ]]; then
+    error "missing required ${FMT_BOLD}Vutun interface gateways${FMT_RESET}"
+    echo
+    help
+    exit 2
+  fi
 
-    start || fatal 2 "unable to start firewall"
-    ;;
-  status)
-    status || fatal 2 "unable to list PF Rules"
-    ;;
-  stop)
-    stop || fatal 2 "unable to stop PF filter"
-    ;;
+  start || fatal 2 "unable to start firewall"
+  ;;
+status)
+  status || fatal 2 "unable to list PF Rules"
+  ;;
+stop)
+  stop || fatal 2 "unable to stop PF filter"
+  ;;
 esac
 
 echo_red "DONE"
-
